import Config

# Use env vars when present so local mix tasks can target dockerized Postgres (e.g. port 55432).
repo_config =
  case System.get_env("DATABASE_URL") do
    nil ->
      [
        username: System.get_env("DB_USERNAME", "postgres"),
        password: System.get_env("DB_PASSWORD", "postgres"),
        hostname: System.get_env("DB_HOST", "localhost"),
        port: String.to_integer(System.get_env("DB_PORT", "5432")),
        database: System.get_env("DB_NAME", "messaging_dev")
      ]

    database_url ->
      [url: database_url]
  end

# Configure your database
config :messaging,
       Messaging.Repo,
       repo_config ++
         [
           stacktrace: true,
           show_sensitive_data_on_connection_error: true,
           pool_size: String.to_integer(System.get_env("POOL_SIZE", "10"))
         ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :messaging, MessagingWeb.Endpoint,
  # Binding to all interfaces to allow access from HAProxy and other machines
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "5qTGSDqniXcV3xg5Xxkj+XygIFuWEov/mXvfbLBYQ8AbAESsIuIZmoDe6Oy3DnMT",
  watchers: [
    npx: [
      "vite",
      "build",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :messaging, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
